Домашка 3
js-tasks-ru/jsbasic-20220711_ekaterina16 pull request #4
Opened 2022-07-22 20:07 UTC by captaincandy2110

2022-07-22 20:08 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-07-22 20:09 UTC, SinimaWath requested changes

2022-07-22 20:09 UTC, SinimaWath commented on 3-module/2-task/index.js
> +  return newArr;
Попробуй переделать на цепочку:

`arr.filter(...).map(...)`

2022-07-22 20:09 UTC, SinimaWath commented on 3-module/3-task/index.js
> +  }
Это очень похоже на map. Давай попробуем его тут использовать:

```
return str
   .split('-')
   .map((word, index) => ...)
   .join('')
```

2022-07-23 05:58 UTC, captaincandy2110 commented on 3-module/2-task/index.js
> +  return newArr;
Я попробовала так:
function filterRange(arr, a, b) {
  return arr.filter(item => arr[item] >= a && arr[item] <= b).map(item => arr[item]);
}

Но console.log( filtered ); возвращает [ 1, 3 ], а не [ 3, 1]

ЧЯДНТ?

2022-07-23 06:12 UTC, captaincandy2110 commented on 3-module/3-task/index.js
> +  }
function camelize(str) {

  return str
    .split('-')
    .map((word, index) => (word[index].charAt(0).toUpperCase() + word[index].slice(1)))
         .join('');
}

Не получается(

2022-07-23 07:30 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-07-23 11:10 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2022-07-23 11:36 UTC, SinimaWath approved these changes

2022-07-23 11:37 UTC, merged