Домашка 7.3
js-tasks-ru/jsbasic-20220711_ekaterina16 pull request #9
Opened 2022-08-12 15:50 UTC by captaincandy2110

2022-08-12 15:51 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-08-13 09:37 UTC, SinimaWath requested changes

2022-08-13 09:37 UTC, SinimaWath commented on 7-module/3-task/index.js
> +    slider.addEventListener('click', (event)=> { this.onSliderClickEvent(event);});
`slider.addEventListener('click', this.onSliderClickEvent(event))`

2022-08-13 09:37 UTC, SinimaWath commented on 7-module/3-task/index.js
>    constructor({ steps, value = 0 }) {
Если выставят value = 3, то слайдер будет работать неправильно. Так как не будет выбран 3-ий шаг

2022-08-13 09:37 UTC, SinimaWath commented on 7-module/3-task/index.js
> +    }
это можно унести в StepSliderTemplate:
```
  return `
    <div class="slider">
        <div class="slider__thumb">
            <span class="slider__value">${value}</span>
        </div>
        <div class="slider__progress"></div>
        <div class="slider__steps">
            ${steps.map(() => '<span></span>').join('')}
        </div>
    </div>`;
```

2022-08-13 09:37 UTC, SinimaWath commented on 7-module/3-task/index.js
> +    progress.style.width = `${valuePercents}%`;
вот эту логику нужно перенести в метод, чтобы можно было ее вызывать в момент `render()`

2022-08-13 09:37 UTC, SinimaWath commented on 7-module/3-task/index.js
> +    return this.#elem.dispatchEvent(sliderChangeEvent);
тут return не нужен

2022-08-14 07:18 UTC, captaincandy2110 commented on 7-module/3-task/index.js
> +    slider.addEventListener('click', (event)=> { this.onSliderClickEvent(event);});
Так не работает
Написала так: 
slider.addEventListener('click', (event) => this.onSliderClickEvent(event));

2022-08-14 10:33 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-08-15 10:26 UTC, SinimaWath approved these changes

2022-08-15 10:26 UTC, merged